work_dir: ${hydra:runtime.cwd}
run_name: default

defaults:
  - logger: tensorboard
  - model: ppo
  - datamodule: ???
  - callbacks: default
  - _self_
  - experiment: ppo_es_ed

seed: 1

datamodule:
 gt_column: Gt_0

predict_subset_frac: 10
train: True

trainer:
  _target_: pytorch_lightning.Trainer
  max_epochs: 10
  log_every_n_steps: 1
  accelerator: auto
#  num_sanity_val_steps: 0 # skip sanity check (convenient for debugging directly in train step)
